[build]
  publish = "."  # Publish the root directory where index.html resides

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[plugins]
  [[plugins]]
    package = "@netlify/netlify-cms-widget-editor"
