[build]
  publish = "."  # Directory to publish

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[plugins]
  [[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true