backend:
  name: git-gateway
  branch: bis

media_folder: "img"
public_folder: "/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown", default_language: "html" }

publish_mode: editorial_workflow
