backend:
  name: git-gateway
  branch: bis

media_folder: "img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", default_language: "html" }
      - label: "Tutorial"
        name: "tutorial"
        file: "tuto.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", default_language: "html" }

  - name: "styles"
    label: "Styles"
    files:
      - label: "Main Stylesheet"
        name: "main_style"
        file: "style/styles.css"
        fields:
          - { label: "CSS Content", name: "body", widget: "code", default_language: "css" }
