backend:
  name: git-gateway
  branch: bis

media_folder: "img"
public_folder: "/img"
public_folder: "/style"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown", default_language: "html" }

  - name: "styles"
    label: "Styles"
    files:
      - label: "Stylesheet"
        name: "style"
        file: "style/styles.css"
        fields:
          - { label: "CSS Content", name: "body", widget: "code", default_language: "css" }
  - name: "styless"
    label: "Styless"
    files:
      - label: "Stylesheeet"
        name: "stylee"
        file: "styles.css"
        fields:
          - { label: "CSS Content", name: "body", widget: "code", default_language: "css" }

publish_mode: editorial_workflow
